-- MySQL Script generated by MySQL Workbench
-- Mon Dec 31 17:03:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8 ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`objectif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`objectif` (
  `idobjectif` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL,
  PRIMARY KEY (`idobjectif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`experience_professionnelle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`experience_professionnelle` (
  `idexperience_professionnelle` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NULL,
  `date` DATE NULL,
  `titre` VARCHAR(255) NULL,
  `content` VARCHAR(255) NULL,
  PRIMARY KEY (`idexperience_professionnelle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`projets_etudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`projets_etudes` (
  `idprojets_professionnels` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `mission` VARCHAR(255) NULL,
  `Compétences_validees` VARCHAR(255) NULL,
  PRIMARY KEY (`idprojets_professionnels`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio`.`projets_professionnels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`projets_professionnels` (
  `idprojets_professionnels` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `mission` VARCHAR(255) NULL,
  PRIMARY KEY (`idprojets_professionnels`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
